### ISSUE TITLE
Planned Feature Tracker

### ISSUE THREAD

**Issue by newwby** [newwby/godot-stat-manager#1]
# Current Planned Feature List

### **Overview**
Whilst the StatManager works as intended, there are some definite revisions I'd like to make once time allows.

### StatManager 2.0

- [ ] migrate experimental StatManager branch to public repo
- [ ] rewrite readme to reflect new StatManager features
- [ ] rewrite readme to reflect

#### Features and Refactors

- [ ] #2
- [ ] + [ ] get stat method that returns all stats of the subject in an organised dict with their names, current values, base values, and modifiers
- [ ] Option to automaticaly clamp (min/max) stat values on return (with optional flags for storing overflow/underflow)
- [ ] Separate stat logic into a separate class so Stat objects (rename StatData?) are smaller
- [ ] update for Godot 4.0

#### Revisions and Bugfixes

- [ ] review usage of assert calls, so no behaviour is contingent on an assert outcome
- [ ] adjust _is_valid_mod to check conditions and assert separately
- [ ] adjust calls to is_valid_mod that use asserts to not rely on assert (check, log error and return/skip if invalid, then assert)
- [ ] add prune_mods return value for whether mods were pruned or not (return can't_resolve if called w/o prune)
- [x] low value floats (-0.99~ to 0.99~)  are getting discarded somewhere, need to diagnose where
  - _**fixed!** it was actually a rounding call leftover in flat mod summation (from before the conversion to float value output only_

---

### **GlobalStat API**

- [x] _verify_args is still checking if subject has property - this is a deprecated design and needs removing!
- [x] replace subject/property check with check if property already exists
